# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'waveform_view_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WaveformViewUI(object):
    def setupUi(self, WaveformViewUI):
        WaveformViewUI.setObjectName("WaveformViewUI")
        WaveformViewUI.resize(1049, 585)
        self.gridLayout_2 = QtWidgets.QGridLayout(WaveformViewUI)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(7, 7, 7, 7)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_start = QtWidgets.QPushButton(WaveformViewUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setObjectName("btn_start")
        self.gridLayout.addWidget(self.btn_start, 2, 0, 1, 1)
        self.chk_write_file = QtWidgets.QCheckBox(WaveformViewUI)
        self.chk_write_file.setObjectName("chk_write_file")
        self.gridLayout.addWidget(self.chk_write_file, 2, 1, 1, 1)
        self.gridWidget_3 = QtWidgets.QWidget(WaveformViewUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridWidget_3.sizePolicy().hasHeightForWidth())
        self.gridWidget_3.setSizePolicy(sizePolicy)
        self.gridWidget_3.setObjectName("gridWidget_3")
        self.wave_layout = QtWidgets.QGridLayout(self.gridWidget_3)
        self.wave_layout.setObjectName("wave_layout")
        self.gridLayout.addWidget(self.gridWidget_3, 1, 0, 1, 2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.chk_3 = QtWidgets.QCheckBox(WaveformViewUI)
        self.chk_3.setObjectName("chk_3")
        self.gridLayout_3.addWidget(self.chk_3, 0, 3, 1, 1)
        self.chk_1 = QtWidgets.QCheckBox(WaveformViewUI)
        self.chk_1.setObjectName("chk_1")
        self.gridLayout_3.addWidget(self.chk_1, 0, 1, 1, 1)
        self.chk_5 = QtWidgets.QCheckBox(WaveformViewUI)
        self.chk_5.setObjectName("chk_5")
        self.gridLayout_3.addWidget(self.chk_5, 0, 5, 1, 1)
        self.chk_4 = QtWidgets.QCheckBox(WaveformViewUI)
        self.chk_4.setObjectName("chk_4")
        self.gridLayout_3.addWidget(self.chk_4, 0, 4, 1, 1)
        self.chk_0 = QtWidgets.QCheckBox(WaveformViewUI)
        self.chk_0.setObjectName("chk_0")
        self.gridLayout_3.addWidget(self.chk_0, 0, 0, 1, 1)
        self.chk_6 = QtWidgets.QCheckBox(WaveformViewUI)
        self.chk_6.setObjectName("chk_6")
        self.gridLayout_3.addWidget(self.chk_6, 0, 6, 1, 1)
        self.chk_2 = QtWidgets.QCheckBox(WaveformViewUI)
        self.chk_2.setObjectName("chk_2")
        self.gridLayout_3.addWidget(self.chk_2, 0, 2, 1, 1)
        self.chk_7 = QtWidgets.QCheckBox(WaveformViewUI)
        self.chk_7.setObjectName("chk_7")
        self.gridLayout_3.addWidget(self.chk_7, 0, 7, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(WaveformViewUI)
        QtCore.QMetaObject.connectSlotsByName(WaveformViewUI)

    def retranslateUi(self, WaveformViewUI):
        _translate = QtCore.QCoreApplication.translate
        WaveformViewUI.setWindowTitle(_translate("WaveformViewUI", "Form"))
        self.btn_start.setText(_translate("WaveformViewUI", "接收数据"))
        self.chk_write_file.setText(_translate("WaveformViewUI", "数据落盘"))
        self.chk_3.setText(_translate("WaveformViewUI", "通道3"))
        self.chk_1.setText(_translate("WaveformViewUI", "通道1"))
        self.chk_5.setText(_translate("WaveformViewUI", "通道5"))
        self.chk_4.setText(_translate("WaveformViewUI", "通道4"))
        self.chk_0.setText(_translate("WaveformViewUI", "通道0"))
        self.chk_6.setText(_translate("WaveformViewUI", "通道6"))
        self.chk_2.setText(_translate("WaveformViewUI", "通道2"))
        self.chk_7.setText(_translate("WaveformViewUI", "通道7"))
