# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cail_from_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CailFromFile(object):
    def setupUi(self, CailFromFile):
        CailFromFile.setObjectName("CailFromFile")
        CailFromFile.resize(549, 487)
        self.gridLayout_2 = QtWidgets.QGridLayout(CailFromFile)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(7, 7, 7, 7)
        self.gridLayout.setObjectName("gridLayout")
        self.table_params = QtWidgets.QTableWidget(CailFromFile)
        self.table_params.setObjectName("table_params")
        self.table_params.setColumnCount(0)
        self.table_params.setRowCount(0)
        self.gridLayout.addWidget(self.table_params, 2, 0, 2, 3)
        self.txt_file_path = QtWidgets.QLabel(CailFromFile)
        self.txt_file_path.setText("")
        self.txt_file_path.setObjectName("txt_file_path")
        self.gridLayout.addWidget(self.txt_file_path, 0, 1, 1, 2)
        self.is_chirp = QtWidgets.QCheckBox(CailFromFile)
        self.is_chirp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.is_chirp.setObjectName("is_chirp")
        self.gridLayout.addWidget(self.is_chirp, 1, 2, 1, 1)
        self.edit_frq_num = QtWidgets.QLineEdit(CailFromFile)
        self.edit_frq_num.setObjectName("edit_frq_num")
        self.gridLayout.addWidget(self.edit_frq_num, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(CailFromFile)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 4, 0, 1, 1)
        self.btn_select_file = QtWidgets.QPushButton(CailFromFile)
        self.btn_select_file.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_select_file.setObjectName("btn_select_file")
        self.gridLayout.addWidget(self.btn_select_file, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(CailFromFile)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(CailFromFile)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(CailFromFile)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 4, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(CailFromFile)
        QtCore.QMetaObject.connectSlotsByName(CailFromFile)

    def retranslateUi(self, CailFromFile):
        _translate = QtCore.QCoreApplication.translate
        CailFromFile.setWindowTitle(_translate("CailFromFile", "Form"))
        self.is_chirp.setText(_translate("CailFromFile", "Chirp"))
        self.edit_frq_num.setText(_translate("CailFromFile", "19"))
        self.pushButton_3.setText(_translate("CailFromFile", "导出"))
        self.btn_select_file.setText(_translate("CailFromFile", "选择文件"))
        self.label_2.setText(_translate("CailFromFile", "频点个数"))
        self.pushButton.setText(_translate("CailFromFile", "导入"))
        self.pushButton_4.setText(_translate("CailFromFile", "开始"))
