# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rcm_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RCMConfig(object):
    def setupUi(self, RCMConfig):
        RCMConfig.setObjectName("RCMConfig")
        RCMConfig.resize(279, 162)
        self.gridLayout_2 = QtWidgets.QGridLayout(RCMConfig)
        self.gridLayout_2.setContentsMargins(7, 7, 7, 7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(RCMConfig)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(RCMConfig)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.select_chnl = QtWidgets.QComboBox(RCMConfig)
        self.select_chnl.setObjectName("select_chnl")
        self.select_chnl.addItem("")
        self.select_chnl.addItem("")
        self.select_chnl.addItem("")
        self.select_chnl.addItem("")
        self.select_chnl.addItem("")
        self.gridLayout.addWidget(self.select_chnl, 0, 1, 1, 1)
        self.txt_transmit_atte = QtWidgets.QLineEdit(RCMConfig)
        self.txt_transmit_atte.setObjectName("txt_transmit_atte")
        self.gridLayout.addWidget(self.txt_transmit_atte, 1, 1, 1, 1)
        self.txt_recv_atte = QtWidgets.QLineEdit(RCMConfig)
        self.txt_recv_atte.setObjectName("txt_recv_atte")
        self.gridLayout.addWidget(self.txt_recv_atte, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(RCMConfig)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.btn_config = QtWidgets.QPushButton(RCMConfig)
        self.btn_config.setObjectName("btn_config")
        self.gridLayout.addWidget(self.btn_config, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(RCMConfig)
        QtCore.QMetaObject.connectSlotsByName(RCMConfig)

    def retranslateUi(self, RCMConfig):
        _translate = QtCore.QCoreApplication.translate
        RCMConfig.setWindowTitle(_translate("RCMConfig", "Form"))
        self.label_2.setText(_translate("RCMConfig", "通道选择"))
        self.label.setText(_translate("RCMConfig", "发射增益(dB)"))
        self.select_chnl.setItemText(0, _translate("RCMConfig", "5"))
        self.select_chnl.setItemText(1, _translate("RCMConfig", "6"))
        self.select_chnl.setItemText(2, _translate("RCMConfig", "7"))
        self.select_chnl.setItemText(3, _translate("RCMConfig", "8"))
        self.select_chnl.setItemText(4, _translate("RCMConfig", "全部"))
        self.label_3.setText(_translate("RCMConfig", "接收增益(dB)"))
        self.btn_config.setText(_translate("RCMConfig", "确定"))
