# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chnlwave.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1015, 140)
        Form.setMinimumSize(QtCore.QSize(0, 140))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chnl_0 = QtWidgets.QLabel(Form)
        self.chnl_0.setMaximumSize(QtCore.QSize(65, 16777215))
        self.chnl_0.setStyleSheet("border:1px;")
        self.chnl_0.setObjectName("chnl_0")
        self.horizontalLayout.addWidget(self.chnl_0)
        self.wave_0 = QtWidgets.QFrame(Form)
        self.wave_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wave_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wave_0.setObjectName("wave_0")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.wave_0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.wave_0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.chnl_0.setText(_translate("Form", "TextLabel"))
