# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exception_handles.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(444, 236)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tips_text = QtWidgets.QLabel(Form)
        self.tips_text.setScaledContents(True)
        self.tips_text.setAlignment(QtCore.Qt.AlignCenter)
        self.tips_text.setObjectName("tips_text")
        self.gridLayout.addWidget(self.tips_text, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tips_text.setText(_translate("Form", "TextLabel"))
